### ISSUE TITLE
The line that connects marker and slider/infobox isn't updated after selecting another marker

### ISSUE THREAD

**Issue by jengeb** [rbb-data/simple-berlin-map#1]
![screenshot from 2018-11-16 12-38-01](https://user-images.githubusercontent.com/3831683/48621906-6220ea00-e9a5-11e8-8c90-a1c77ed95a4c.png)

I clicked on the selected marker but the line doesn't connect this marker with the infobox.

**Comment by errnesto** [comment]
Jap this should be fixed by https://github.com/rbb-data/rbb-data-shared/commit/8732c4df2a1d8655c33a8140211972b1af380a9d. Sou you could just update to the current version of rbb-data-shared and everything should work again.

**Comment by jengeb** [comment]
Perfect! Thanks!
